In [1]:
# Perofrming Sentiment Analysis

import numpy as np
import pandas as pd
import nltk
import string
import re
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize
df = pd.read_csv("C:/Users/rojit/Desktop/Scrape_AmazonReviews/Scrape_AmazonReviews/output.csv", dtype = 'str')
df.head() 

Name                                              Title  \
0         Vara Prasad  \n\n\n\n\n\n\n\n  \n  \n    Camera is not at a...   
1     Abhishek BIswas  \n\n\n\n\n\n\n\n  \n  \n    10 DAYS REVIEW- Th...   
2        Abdul Lateef  \n\n\n\n\n\n\n\n  \n  \n    The Performance Be...   
3  Rajendra Singh rao      \n\n\n\n\n\n\n\n  \n    तकनीकी खामी\n  \n  \n   
4       Neelabh Sinha  \n\n\n\n\n\n\n\n  \n  \n    Detailed personal ...   

               Rating                                            Comment  
0  1.0 out of 5 stars  \n\n\n\n\n\n\n\n\n\n  \n  \n    \n  After one ...  
1  5.0 out of 5 stars  \n\n\n\n\n\n\n\n\n\n  \n  \n    \n  ### IN SHO...  
2  4.0 out of 5 stars  \n\n\n\n\n\n\n\n\n\n  \n  \n    \n  Feedback a...  
3  5.0 out of 5 stars  \n\n\n\n\n\n\n\n\n\n  \n    \n  में रेडमी के इ...  
4  4.0 out of 5 stars  \n\n\n\n\n\n\n\n\n\n  \n  \n    \n  Writing th...

In [2]:
#removing unwanted \n(next lines)
df = df.replace('\n','', regex=True)
df.head()

Name                                              Title  \
0         Vara Prasad              Camera is not at all working proper     
1     Abhishek BIswas          10 DAYS REVIEW- There are issues(scree...   
2        Abdul Lateef                     The Performance Beast Indeed     
3  Rajendra Singh rao                                    तकनीकी खामी       
4       Neelabh Sinha          Detailed personal review after 1 week ...   

               Rating                                            Comment  
0  1.0 out of 5 stars            After one month intense use  I am he...  
1  5.0 out of 5 stars            ### IN SHORT ###Overall great phone....  
2  4.0 out of 5 stars            Feedback after using it for 20 daysP...  
3  5.0 out of 5 stars          में रेडमी के इस उपकरण से असंतुष्ट एवम ...  
4  4.0 out of 5 stars            Writing this review after 7 days of ...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     190 non-null    object
 1   Title    190 non-null    object
 2   Rating   190 non-null    object
 3   Comment  190 non-null    object
dtypes: object(4)
memory usage: 6.1+ KB


In [4]:
df.drop(['Name', 'Title'], axis = 1)

Rating                                            Comment
0    1.0 out of 5 stars            After one month intense use  I am he...
1    5.0 out of 5 stars            ### IN SHORT ###Overall great phone....
2    4.0 out of 5 stars            Feedback after using it for 20 daysP...
3    5.0 out of 5 stars          में रेडमी के इस उपकरण से असंतुष्ट एवम ...
4    4.0 out of 5 stars            Writing this review after 7 days of ...
..                  ...                                                ...
185  1.0 out of 5 stars            Battery life is excellent but camera...
186  1.0 out of 5 stars            Several times mobile get hanged and ...
187  4.0 out of 5 stars            This is one of the best android cell...
188  5.0 out of 5 stars            Very satisfied , looks gorgeous, and...
189  4.0 out of 5 stars            Worth For money. GOOD QUALITY, SLOW ...

[190 rows x 2 columns]

In [5]:
df.head()


Name                                              Title  \
0         Vara Prasad              Camera is not at all working proper     
1     Abhishek BIswas          10 DAYS REVIEW- There are issues(scree...   
2        Abdul Lateef                     The Performance Beast Indeed     
3  Rajendra Singh rao                                    तकनीकी खामी       
4       Neelabh Sinha          Detailed personal review after 1 week ...   

               Rating                                            Comment  
0  1.0 out of 5 stars            After one month intense use  I am he...  
1  5.0 out of 5 stars            ### IN SHORT ###Overall great phone....  
2  4.0 out of 5 stars            Feedback after using it for 20 daysP...  
3  5.0 out of 5 stars          में रेडमी के इस उपकरण से असंतुष्ट एवम ...  
4  4.0 out of 5 stars            Writing this review after 7 days of ...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     190 non-null    object
 1   Title    190 non-null    object
 2   Rating   190 non-null    object
 3   Comment  190 non-null    object
dtypes: object(4)
memory usage: 6.1+ KB


In [7]:
# Converting all text to lowercase
df['Comment'] = df['Comment'].str.lower()
df.head()

Name                                              Title  \
0         Vara Prasad              Camera is not at all working proper     
1     Abhishek BIswas          10 DAYS REVIEW- There are issues(scree...   
2        Abdul Lateef                     The Performance Beast Indeed     
3  Rajendra Singh rao                                    तकनीकी खामी       
4       Neelabh Sinha          Detailed personal review after 1 week ...   

               Rating                                            Comment  
0  1.0 out of 5 stars            after one month intense use  i am he...  
1  5.0 out of 5 stars            ### in short ###overall great phone....  
2  4.0 out of 5 stars            feedback after using it for 20 daysp...  
3  5.0 out of 5 stars          में रेडमी के इस उपकरण से असंतुष्ट एवम ...  
4  4.0 out of 5 stars            writing this review after 7 days of ...

In [8]:
# Removing the punctuation marks

def remove_punc(text):
    text = "".join([char for char in text if char not in string.punctuation])
    text = re.sub('[0-9]+', '', text)
    return text

df['Comment'] = df['Comment'].apply(lambda x: remove_punc(x))
df.head()

Name                                              Title  \
0         Vara Prasad              Camera is not at all working proper     
1     Abhishek BIswas          10 DAYS REVIEW- There are issues(scree...   
2        Abdul Lateef                     The Performance Beast Indeed     
3  Rajendra Singh rao                                    तकनीकी खामी       
4       Neelabh Sinha          Detailed personal review after 1 week ...   

               Rating                                            Comment  
0  1.0 out of 5 stars            after one month intense use  i am he...  
1  5.0 out of 5 stars             in short overall great phone i had ...  
2  4.0 out of 5 stars            feedback after using it for  dayspro...  
3  5.0 out of 5 stars          में रेडमी के इस उपकरण से असंतुष्ट एवम ...  
4  4.0 out of 5 stars            writing this review after  days of u...

In [9]:
#removing non english comments
dataset = df[df['Comment'].map(lambda x: x.isascii())]
dataset.reset_index(inplace = True)

dataset.pop('index')
dataset.head()

Name                                              Title  \
0    Vara Prasad              Camera is not at all working proper     
1   Abdul Lateef                     The Performance Beast Indeed     
2  Neelabh Sinha          Detailed personal review after 1 week ...   
3     kanchan m.                                  Redmi note 9pro     
4      Aman Rana          A powerful monster with amazing batter...   

               Rating                                            Comment  
0  1.0 out of 5 stars            after one month intense use  i am he...  
1  4.0 out of 5 stars            feedback after using it for  dayspro...  
2  4.0 out of 5 stars            writing this review after  days of u...  
3  5.0 out of 5 stars            just amazingcamera battery and perfo...  
4  4.0 out of 5 stars            i am writing this review after one m...

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     158 non-null    object
 1   Title    158 non-null    object
 2   Rating   158 non-null    object
 3   Comment  158 non-null    object
dtypes: object(4)
memory usage: 5.1+ KB


In [11]:
#deleting unwanter columns
dataset.pop('Name')
dataset.pop('Title')

0                  Camera is not at all working proper  
1                         The Performance Beast Indeed  
2              Detailed personal review after 1 week ...
3                                      Redmi note 9pro  
4              A powerful monster with amazing batter...
                             ...                        
153                                     Very bad phone  
154            Worse phone ever, not recommended to b...
155                                          Worth it!  
156                     Redmi note 9 Pro excellent Buy  
157            Amazing Experience with Amazon.. Super...
Name: Title, Length: 158, dtype: object

In [12]:
dataset.head()

Rating                                            Comment
0  1.0 out of 5 stars            after one month intense use  i am he...
1  4.0 out of 5 stars            feedback after using it for  dayspro...
2  4.0 out of 5 stars            writing this review after  days of u...
3  5.0 out of 5 stars            just amazingcamera battery and perfo...
4  4.0 out of 5 stars            i am writing this review after one m...

In [13]:
# converting rating to integer
dataset['Rating'] = dataset['Rating'].str.replace('out of 5 stars','')

dataset['Rating'] = pd.to_numeric(dataset['Rating'], errors='coerce').fillna(0)
dataset['Rating'] = dataset['Rating'].astype('int64')
dataset.head()

C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docum

Rating                                            Comment
0       1            after one month intense use  i am he...
1       4            feedback after using it for  dayspro...
2       4            writing this review after  days of u...
3       5            just amazingcamera battery and perfo...
4       4            i am writing this review after one m...

In [14]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Rating   158 non-null    int64 
 1   Comment  158 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.6+ KB


In [15]:
# remove numbers from comment
dataset['Comment'] = dataset['Comment'].str.replace('\d+', '')
dataset.head()

C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Rating                                            Comment
0       1            after one month intense use  i am he...
1       4            feedback after using it for  dayspro...
2       4            writing this review after  days of u...
3       5            just amazingcamera battery and perfo...
4       4            i am writing this review after one m...

In [16]:
# Tokenizing the words (Separating words from a sentence)
comments = dataset['Comment']
dataset['Comment'] = comments.apply(word_tokenize)
dataset.head()

C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Rating                                            Comment
0       1  [after, one, month, intense, use, i, am, here,...
1       4  [feedback, after, using, it, for, dayspros, so...
2       4  [writing, this, review, after, days, of, usage...
3       5  [just, amazingcamera, battery, and, performanc...
4       4  [i, am, writing, this, review, after, one, mon...

In [17]:
#performing lemmatization
wn = nltk.WordNetLemmatizer()

def lemmatizer(text):
    text = [wn.lemmatize(word) for word in text]
    return text

dataset['Comment'] = dataset['Comment'].apply(lambda x: lemmatizer(x))
dataset.head()

C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Rating                                            Comment
0       1  [after, one, month, intense, use, i, am, here,...
1       4  [feedback, after, using, it, for, dayspros, so...
2       4  [writing, this, review, after, day, of, usageg...
3       5  [just, amazingcamera, battery, and, performanc...
4       4  [i, am, writing, this, review, after, one, mon...

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Rating   158 non-null    int64 
 1   Comment  158 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.6+ KB


In [19]:
null_counts = dataset.isnull().sum()
null_counts

Rating     0
Comment    0
dtype: int64

In [20]:
# Forming a sentence from the remaining words

corpus = []
for i in range(0, 158):
    review = ' '.join(dataset['Comment'][i])
    corpus.append(review)

print("Corpus", corpus)

Corpus ['after one month intense use i am here to submit feedbackthis is very worst worst worst model phone in redmi series because with in day after purchase i met the problem with this i thought it may resolved automatically while updating phone but it doe happened the main problem in this phone that what ever the xiomi promoted in this phone like quadra camera is not at all opening while opening saying that opening in camera is error please restart so many time restarted eventhough no response and phone also strucking while usingi request all of you to kindly not to buy this phone', 'feedback after using it for dayspros solid sturdy and robust materialpremium look and feelsolid battery performance no matter what you do it will last for a day and a halffull speed without any lag thanks to qualcomm snapdragon miui ha the best interface eververy good camera especially night modecrisp hd display with a cool dot notchside mounted fingerprint is awesomecons is a bit bulky and heavy with t

In [21]:
# Classifying Reviews as positive/negative/neutral based on ratings

classify = []
for i in range(0, 158):
    if dataset['Rating'][i] > 3:
        classify.append(1)
    elif dataset['Rating'][i] < 3: 
        classify.append(-1)
    else:
        classify.append(0)


dataset['Classify'] = classify
dataset.head()

C:\Users\rojit\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]


Rating                                            Comment  Classify
0       1  [after, one, month, intense, use, i, am, here,...        -1
1       4  [feedback, after, using, it, for, dayspros, so...         1
2       4  [writing, this, review, after, day, of, usageg...         1
3       5  [just, amazingcamera, battery, and, performanc...         1
4       4  [i, am, writing, this, review, after, one, mon...         1

In [22]:
# Vectorizing the words and counting the frequency for each
# Extracting the features
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 2].values
print(cv.vocabulary_)

{'after': 38, 'one': 764, 'month': 720, 'use': 1376, 'am': 63, 'here': 569, 'to': 1290, 'submit': 1206, 'is': 626, 'very': 1404, 'worst': 1475, 'model': 716, 'phone': 797, 'in': 610, 'redmi': 946, 'series': 1085, 'because': 170, 'with': 1464, 'day': 342, 'purchase': 879, 'the': 1259, 'problem': 836, 'this': 1277, 'thought': 1282, 'it': 636, 'may': 700, 'resolved': 988, 'automatically': 128, 'while': 1454, 'updating': 1360, 'but': 251, 'doe': 395, 'happened': 532, 'main': 690, 'that': 1255, 'what': 1447, 'ever': 424, 'xiomi': 1485, 'promoted': 858, 'like': 671, 'quadra': 888, 'camera': 268, 'not': 749, 'at': 117, 'all': 48, 'opening': 770, 'saying': 1045, 'error': 420, 'please': 810, 'restart': 996, 'so': 1138, 'many': 693, 'time': 1287, 'restarted': 997, 'no': 745, 'response': 992, 'and': 75, 'also': 59, 'strucking': 1198, 'usingi': 1390, 'request': 979, 'of': 757, 'you': 1491, 'kindly': 654, 'buy': 254, 'feedback': 451, 'using': 1389, 'for': 467, 'solid': 1141, 'sturdy': 1204, 'robust

In [23]:
#Splitting data into train, test and validation set

X_train = X[0:90, :]

X_test = X[90:128, :]

y_train = y[0:90]

y_test = y[90:128]

X_val = X[128:159, :]

y_val = y[128:159]


In [24]:
# Using KNN

classifier = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p=2)
classifier.fit(X_train,y_train)

y_pred_knn0 = classifier.predict(X_train)
acc_knn0 = accuracy_score(y_train, y_pred_knn0)*100
print('Train Accuracy from KNN:', acc_knn0)

y_pred_knn = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)
acc_knn = accuracy_score(y_test, y_pred_knn)*100
print('Test Accuracy from KNN:', acc_knn)
print(classification_report(y_test, y_pred_knn))

Train Accuracy from KNN: 67.77777777777779
[[15  0  1]
 [ 5  0  3]
 [ 4  2  8]]
Test Accuracy from KNN: 60.526315789473685
              precision    recall  f1-score   support

          -1       0.62      0.94      0.75        16
           0       0.00      0.00      0.00         8
           1       0.67      0.57      0.62        14

    accuracy                           0.61        38
   macro avg       0.43      0.50      0.46        38
weighted avg       0.51      0.61      0.54        38



In [25]:
#Using LogisticRegression

lr = LogisticRegression(max_iter=158) 
lr.fit(X_train, y_train)
y_pred_lr0 = lr.predict(X_train)
acc_lr0 = accuracy_score(y_train, y_pred_lr0)*100
print(' Train Accuracy from Logistic Regression classifier:', acc_lr0)

y_pred_lr = lr.predict(X_test)
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
acc_lr = accuracy_score(y_test, y_pred_lr)*100
print(' Test Accuracy from Logistic Regression classifier:', acc_lr)
print(classification_report(y_test, y_pred_lr))

 Train Accuracy from Logistic Regression classifier: 100.0
[[14  0  2]
 [ 3  0  5]
 [ 1  2 11]]
 Test Accuracy from Logistic Regression classifier: 65.78947368421053
              precision    recall  f1-score   support

          -1       0.78      0.88      0.82        16
           0       0.00      0.00      0.00         8
           1       0.61      0.79      0.69        14

    accuracy                           0.66        38
   macro avg       0.46      0.55      0.50        38
weighted avg       0.55      0.66      0.60        38



In [26]:
# Random forest classifier

RF= RandomForestClassifier(n_estimators= 16, criterion="entropy")
RF.fit(X_train, y_train)
Rpred0 = RF.predict(X_train)
acc_rf0 = accuracy_score(y_train, Rpred0)*100
print(' Train Accuracy from Random Forest classifier:', acc_rf0)

Rpred = RF.predict(X_test)
cm = confusion_matrix(y_test, Rpred)
print(cm)
acc_rf = accuracy_score(y_test, Rpred)*100
print(' Test Accuracy from Random Forest classifier:', acc_rf)
print(classification_report(y_test, Rpred))

 Train Accuracy from Random Forest classifier: 98.88888888888889
[[14  0  2]
 [ 3  0  5]
 [ 3  0 11]]
 Test Accuracy from Random Forest classifier: 65.78947368421053
              precision    recall  f1-score   support

          -1       0.70      0.88      0.78        16
           0       0.00      0.00      0.00         8
           1       0.61      0.79      0.69        14

    accuracy                           0.66        38
   macro avg       0.44      0.55      0.49        38
weighted avg       0.52      0.66      0.58        38



C:\Users\rojit\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
# printing pretty table
from prettytable import PrettyTable
Table = PrettyTable(["Algorithm", "Train Accuracy","Test Accuracy"])
Table.add_row(["KNN", acc_knn0, acc_knn])
Table.add_row(["Logistic Regression", acc_lr0, acc_lr])
Table.add_row(["Random Forest", acc_rf0, acc_rf])
print(Table)

+---------------------+-------------------+--------------------+
|      Algorithm      |   Train Accuracy  |   Test Accuracy    |
+---------------------+-------------------+--------------------+
|         KNN         | 67.77777777777779 | 60.526315789473685 |
| Logistic Regression |       100.0       | 65.78947368421053  |
|    Random Forest    | 98.88888888888889 | 65.78947368421053  |
+---------------------+-------------------+--------------------+
