In [1]:
# Content based Movie recommendation
import pandas as pd
import numpy as np
import nltk
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from rake_nltk import Rake   
import warnings
warnings.filterwarnings("ignore")

In [2]:
#Movie rating dataset link --> https://query.data.world/s/uikepcpffyo2nhig52xxeevdialfl7

dataframe = pd.read_csv('https://query.data.world/s/uikepcpffyo2nhig52xxeevdialfl7')
dataframe.head()

Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  ... tomatoConsensus  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...  ...             NaN   
1  Marlon Brando, Al Pacino, James Caan, Richard ...  ...             NaN   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...  ...             NaN   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...  ...             NaN   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....  ...             NaN   

  tomatoUserMeter tomatoUserRating tomatoUserReviews  \
0             NaN              NaN               NaN   
1             NaN              NaN               NaN   
2             NaN              NaN               NaN   
3             NaN              NaN               NaN   
4             NaN              NaN               NaN   

                                           tomatoURL          DVD  \
0  http://www.rottentomatoes.com/m/shawshank_rede...  27 Jan 1998   
1         http://www.rottentomatoes.com/m/godfather/  09 Oct 2001   
2  http://www.rottentomatoes.com/m/godfather_part...  24 May 2005   
3   http://www.rottentomatoes.com/m/the_dark_knight/  09 Dec 2008   
4  http://www.rottentomatoes.com/m/1000013-12_ang...  06 Mar 2001   

      BoxOffice                       Production  \
0           NaN                Columbia Pictures   
1           NaN               Paramount Pictures   
2           NaN               Paramount Pictures   
3  $533,316,061  Warner Bros. Pictures/Legendary   
4           NaN             Criterion Collection   

                                             Website Response  
0                                                NaN     True  
1                        http://www.thegodfather.com     True  
2                       http://www.thegodfather.com/     True  
3               http://thedarkknight.warnerbros.com/     True  
4  http://www.criterion.com/films/27871-12-angry-men     True  

[5 rows x 38 columns]

In [3]:
dataframe.shape

(250, 38)

In [4]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         250 non-null    int64  
 1   Title              250 non-null    object 
 2   Year               250 non-null    int64  
 3   Rated              250 non-null    object 
 4   Released           248 non-null    object 
 5   Runtime            250 non-null    object 
 6   Genre              250 non-null    object 
 7   Director           250 non-null    object 
 8   Writer             249 non-null    object 
 9   Actors             250 non-null    object 
 10  Plot               250 non-null    object 
 11  Language           250 non-null    object 
 12  Country            250 non-null    object 
 13  Awards             245 non-null    object 
 14  Poster             250 non-null    object 
 15  Ratings.Source     250 non-null    object 
 16  Ratings.Value      250 non

In [5]:
# creating dataframe with only required columns
df = dataframe[['Title','Director', 'Actors', 'Plot', 'Genre']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Title     250 non-null    object
 1   Director  250 non-null    object
 2   Actors    250 non-null    object
 3   Plot      250 non-null    object
 4   Genre     250 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB


In [6]:
df.head()

Title              Director  \
0  The Shawshank Redemption        Frank Darabont   
1             The Godfather  Francis Ford Coppola   
2    The Godfather: Part II  Francis Ford Coppola   
3           The Dark Knight     Christopher Nolan   
4              12 Angry Men          Sidney Lumet   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot                 Genre  
0  Two imprisoned men bond over a number of years...          Crime, Drama  
1  The aging patriarch of an organized crime dyna...          Crime, Drama  
2  The early life and career of Vito Corleone in ...          Crime, Drama  
3  When the menace known as the Joker emerges fro...  Action, Crime, Drama  
4  A jury holdout attempts to prevent a miscarria...          Crime, Drama

In [7]:
#checking for null values
df.isnull().sum()

Title       0
Director    0
Actors      0
Plot        0
Genre       0
dtype: int64

In [8]:
# describing the dataset
df.describe()

Title          Director  \
count              250               250   
unique             250               155   
top     Reservoir Dogs  Alfred Hitchcock   
freq                 1                 9   

                                                   Actors  \
count                                                 250   
unique                                                248   
top     Mark Hamill, Harrison Ford, Carrie Fisher, Bil...   
freq                                                    2   

                                                     Plot  Genre  
count                                                 250    250  
unique                                                250    110  
top     A psychotic socialite confronts a pro tennis s...  Drama  
freq                                                    1     19

In [9]:
# remove punctuation
df['Plot'] = df['Plot'].str.replace('[^\w\s]','')
df.head()

Title              Director  \
0  The Shawshank Redemption        Frank Darabont   
1             The Godfather  Francis Ford Coppola   
2    The Godfather: Part II  Francis Ford Coppola   
3           The Dark Knight     Christopher Nolan   
4              12 Angry Men          Sidney Lumet   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot                 Genre  
0  Two imprisoned men bond over a number of years...          Crime, Drama  
1  The aging patriarch of an organized crime dyna...          Crime, Drama  
2  The early life and career of Vito Corleone in ...          Crime, Drama  
3  When the menace known as the Joker emerges fro...  Action, Crime, Drama  
4  A jury holdout attempts to prevent a miscarria...          Crime, Drama

In [10]:
#extracting key words from plot using rake
df['Key_words'] = ''  
r = Rake()   

for index, row in df.iterrows():
    r.extract_keywords_from_text(row['Plot'])   
    key_words_dict_scores = r.get_word_degrees()   
    row['Key_words'] = list(key_words_dict_scores.keys())   
df.head()

Title              Director  \
0  The Shawshank Redemption        Frank Darabont   
1             The Godfather  Francis Ford Coppola   
2    The Godfather: Part II  Francis Ford Coppola   
3           The Dark Knight     Christopher Nolan   
4              12 Angry Men          Sidney Lumet   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot                 Genre  \
0  Two imprisoned men bond over a number of years...          Crime, Drama   
1  The aging patriarch of an organized crime dyna...          Crime, Drama   
2  The early life and career of Vito Corleone in ...          Crime, Drama   
3  When the menace known as the Joker emerges fro...  Action, Crime, Drama   
4  A jury holdout attempts to prevent a miscarria...          Crime, Drama   

                                           Key_words  
0  [number, common, decency, years, finding, sola...  
1  [aging, patriarch, clandestine, empire, organi...  
2  [portrayed, tightens, early, life, vito, corle...  
3  [physical, tests, dark, knight, must, accept, ...  
4  [forcing, justice, jury, holdout, attempts, pr...

In [11]:
# to extract all data into lists
df['Genre'] = df['Genre'].map(lambda x: x.split(','))
df['Actors'] = df['Actors'].map(lambda x: x.split(',')[:3])
df['Director'] = df['Director'].map(lambda x: x.split(','))

# create unique identity names by merging first & last name into one word, convert to lowercase
for index, row in df.iterrows():
    row['Genre'] = [x.lower().replace(' ','') for x in row['Genre']]
    row['Actors'] = [x.lower().replace(' ','') for x in row['Actors']]
    row['Director'] = [x.lower().replace(' ','') for x in row['Director']]

df.head()

Title              Director  \
0  The Shawshank Redemption       [frankdarabont]   
1             The Godfather  [francisfordcoppola]   
2    The Godfather: Part II  [francisfordcoppola]   
3           The Dark Knight    [christophernolan]   
4              12 Angry Men         [sidneylumet]   

                                       Actors  \
0      [timrobbins, morganfreeman, bobgunton]   
1         [marlonbrando, alpacino, jamescaan]   
2       [alpacino, robertduvall, dianekeaton]   
3  [christianbale, heathledger, aaroneckhart]   
4      [martinbalsam, johnfiedler, leej.cobb]   

                                                Plot                   Genre  \
0  Two imprisoned men bond over a number of years...          [crime, drama]   
1  The aging patriarch of an organized crime dyna...          [crime, drama]   
2  The early life and career of Vito Corleone in ...          [crime, drama]   
3  When the menace known as the Joker emerges fro...  [action, crime, drama]   
4  A jury holdout attempts to prevent a miscarria...          [crime, drama]   

                                           Key_words  
0  [number, common, decency, years, finding, sola...  
1  [aging, patriarch, clandestine, empire, organi...  
2  [portrayed, tightens, early, life, vito, corle...  
3  [physical, tests, dark, knight, must, accept, ...  
4  [forcing, justice, jury, holdout, attempts, pr...

In [12]:
# combine 4 columnss under Bag_of_words column
df['Bag_of_words'] = ''
columns = ['Genre', 'Director', 'Actors', 'Key_words']

for index, row in df.iterrows():
    words = ''
    for col in columns:
        words += ' '.join(row[col]) + ' '
    row['Bag_of_words'] = words
    
# strip white spaces infront and behind, replace multiple whitespaces (if any)
df['Bag_of_words'] = df['Bag_of_words'].str.strip().str.replace('   ', ' ').str.replace('  ', ' ')

df = df[['Title','Bag_of_words']]
df.head()

Title                                       Bag_of_words
0  The Shawshank Redemption  crime drama frankdarabont timrobbins morganfre...
1             The Godfather  crime drama francisfordcoppola marlonbrando al...
2    The Godfather: Part II  crime drama francisfordcoppola alpacino robert...
3           The Dark Knight  action crime drama christophernolan christianb...
4              12 Angry Men  crime drama sidneylumet martinbalsam johnfiedl...

In [13]:
# Vectorize  Bag of words
count = CountVectorizer()
count_matrix = count.fit_transform(df['Bag_of_words'])

# using cosine_similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.15789474 0.13764944 ... 0.05407381 0.05407381 0.05564149]
 [0.15789474 1.         0.36706517 ... 0.05407381 0.05407381 0.05564149]
 [0.13764944 0.36706517 1.         ... 0.04714045 0.04714045 0.04850713]
 ...
 [0.05407381 0.05407381 0.04714045 ... 1.         0.05555556 0.0571662 ]
 [0.05407381 0.05407381 0.04714045 ... 0.05555556 1.         0.0571662 ]
 [0.05564149 0.05564149 0.04850713 ... 0.0571662  0.0571662  1.        ]]


In [14]:
#creating index list for movie titles
indices = pd.Series(df['Title'])
indices[:5]

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [17]:
# To get the top 10 recomended movies based on similarity 
def recommend(title, cosine_sim = cosine_sim):
    recommended_movies = []
    idx = indices[indices == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)  
    top_10_indices = list(score_series.iloc[1:11].index)   
    
    
    for i in top_10_indices:   
        recommended_movies.append(list(df['Title'])[i])
        
    return recommended_movies
print("Recomended movies are : ")
recommend('Slumdog Millionaire')

Recomended movies are : 


['Trainspotting',
 'The Green Mile',
 'Lion',
 'Goodfellas',
 'Cool Hand Luke',
 'Room',
 'The Graduate',
 'La La Land',
 'The Killing',
 "Hachi: A Dog's Tale"]